### ISSUE TITLE
Support latest version of app

### ISSUE THREAD

**Issue by lightswitch2159** [jwoglom/tconnectpatcher#1]
Up until the latest version of the app it was very buggy (logging you out, disconnecting from pump, etc) any chance we can get this to work for the latest version? 1.6 (11a)

**Comment by ramboozer** [comment]
I have all these problems with just using 1.6 (11a) APK non patched. This is an app problem I believe

**Comment by lightswitch2159** [comment]
> I have all these problems with just using 1.6 (11a) APK non patched. This is an app problem I believe

Oh I have them also with the unpatched app, just _far_ less often than with the previous versions!

**Comment by ramboozer** [comment]
> 

I was trying to get TSlim Tech support on the phone to figure out if it was a me problem or a them problem...Anytime I open the app..asks me to login. Very frustrating especially when I don't ever actually close out of the app just hide it in the background.

**Comment by kswick** [comment]
Is is related to the fix in version 1.6.1 (11b) that was just released by Tandem on Dec 6, 2021?

**Comment by jwoglom** [comment]
Unfortunately, starting with version 1.4, Tandem has enabled DexProtector in the Android app. This adds a series of checks which detects whether the app has been recompiled and, if it detects any modifications, prevents it from starting. This makes applying this change much more difficult than before.

With more work, it may be possible to work around this issue, but I haven't found a solution yet. I'm working on approaching this from a different angle, potentially building an open-source app which communicates with the pump over BT independently of the official app. (Think what xDrip is to the official Dexcom app.) This is in the very early stages and I don't have anything to share about it yet.

The fact that the Tandem app randomly logs out seems to be a bug on their end, unconnected to tconnectpatcher as far as I know. I haven't experienced it since updating to the latest version.

**Comment by jwoglom** [comment]
Update -- while we are unable to re-compile newer versions of the app than v1.2, I've found a way to work around the bug on Tandem's side which prevented old versions of the app from functioning. So tconnectpatcher should be usable again on v1.2

@kswick @ramboozer @lightswitch2159
