### ISSUE TITLE
Unsupported Android?

### ISSUE THREAD

**Issue by Miquest** [jwoglom/tconnectpatcher#5]
Hi,
does the patch also mean that the T:Connect Mobile App can also be used on devices that are not officially supported? I think that would be a great help for many, because the Apple/Samsung Tandem requirement is extremely annoying.
Could you implement this if it isn't?

Kind regards,
Thorin

**Comment by jwoglom** [comment]
As far as I can tell, the version of the app that the patcher runs on doesn't have any compatibility checks outside of checking the Android version. It seems to block <=Android 7 and Android 11 (but allows Android 12+).

I never noticed this since I only have Pixel devices with Android 12, but if it would help I can pretty easily edit the app to have no compatibility checks at all. Do note that there is no mobile bolus here in this version though, so this is just for display.

**Comment by Miquest** [comment]
Ah okay, great to know!
I live in Germany where the T:Connect mobile app is not yet available. But I would be interested to know if I will have to buy a new phone to use the features when it becomes available.
Is version 1.2 really the only possible app version? When I decompiled the APK, there was a directory that at first glance contained the compatibility checks.
Perhaps it is possible to manipulate this in newer versions as well? In any case, what you have programmed is a first step towards manufacturer-independent use of the T:Connect Mobile application.
A big thank you to everyone who is delving into the deeper levels of medical technology and sharing their findings with others!

**Comment by jwoglom** [comment]
Since you're in a region where t:connect isn't supported I'd suggest checking out https://github.com/jwoglom/pumpx2 -- just keep in mind that it is in a very early state. Unfortunately decompiling and making edits on newer versions of the app isn't super feasible. It might be possible to edit the v1.2 of the app to not require a t:connect login and just be display only, for your use case, but I think pumpx2 is a better forward-looking solution as it allows the community to build anything on top of the pump bluetooth protocol.

**Comment by Miquest** [comment]
Okay, I'll check that out, thank you!
